name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          # macOS 12.4 + Xcode 13.4.1
          - name: "macOS 12.4 + Xcode 13.4.1"
            os: macos-12
            compiler: xcode
            version: "13.4.1"
          # macOS 11.6 + Xcode 12.5.1
          - name: "macOS 11.6 + Xcode 12.5.1"
            os: macos-11
            compiler: xcode
            version: "12.5.1"

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install Packages
      run: |
        brew install openal-soft
    - name: Configure Compiler
      run: |
        if [ "${{ matrix.compiler }}" = "gcc" ]; then
          echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
          echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
        else
          ls -ls /Applications/
          sudo xcode-select -switch /Applications/Xcode_${{ matrix.version }}.app
          echo "CC=clang" >> $GITHUB_ENV
          echo "CXX=clang++" >> $GITHUB_ENV
        fi
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release ..
    - name: Build
      run: cd build && make
    - name: Run Unit Test
      run: /Users/runner/work/CubbyTower/CubbyTower/build/bin/UnitTests