name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    strategy:
      matrix:
        include:
          # Windows Server 2019 + Visual Studio 2019
          - name: "Windows Server 2019 + Visual Studio 2019"
            os: windows-2019
          # Windows Server 2022 + Visual Studio 2022
          - name: "Windows Server 2022 + Visual Studio 2022"
            os: windows-2022

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Configure Build
      run: mkdir build && cd build && cmake -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_BUILD_TYPE=Release ..
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - name: Build
      run: cd build && MSBuild.exe CubbyTower.sln /p:Configuration=Release
    - name: Run Unit Test
      run: /a/CubbyTower/CubbyTower/build/bin/Release/UnitTests.exe